FROM public.ecr.aws/docker/library/node:20-alpine3.19

WORKDIR /app

RUN apk add --no-cache tzdata openssl

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 8001 9229

CMD ["npm", "run", "start:dev"]